### ISSUE TITLE
Unable to download large sketch

### ISSUE THREAD

**Issue by megacct** [arduino-libraries/Arduino_Portenta_OTA#54]
Hi,

I've hit a problem using the download function which returns a negative result with large sketches. I've done some testing and found the sketch footprint at the 'tipping point' between success and failure is:

Sketch uses 532732 bytes (27%) of program storage space. Maximum is 1966080 bytes.
Global variables use 331976 bytes (63%) of dynamic memory, leaving 191648 bytes for local variables. Maximum is 523624 bytes.

The download for this sketch works but if I then add, let's say, delay(1) then I get a negative return from the download function.

Interestingly, the return code from download is +32756 without the delay(1) and -32768 with the delay added. Is there a 32KB limit in the download code?

Thanks

**Comment by pennam** [comment]
@megacct are you using `download` or `downloadAndDecompress` function?

**Comment by megacct** [comment]
download

**Comment by megacct** [comment]
@pennam Doh! just spotted my variable for the result is declared at int16_t. Don't know how that happened but tested again with 32 bit and working great again. Sorry to trouble you
